# Generated by Django 4.0.1 on 2022-01-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
