# Generated by Django 4.0.1 on 2022-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_create_time_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_index', ' Can View Index '),)},
        ),
    ]
