# Generated by Django 4.0.1 on 2022-01-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_index', ' Can View Index '), ('change_server_status', 'Can change the status of server'))},
        ),
    ]
