# Generated by Django 4.0.1 on 2022-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Asia/Shanghai', max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
